import { useState } from "react";

import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Preview from "./components/Preview";
import EditorForm from "./components/EditorForm";
import { useMediaQuery } from "@mui/material";
import Bar from "./components/Bar";

export default function Home() {
  const isBigScreen = useMediaQuery("(min-width: 900px)");
  const [isEditorShown, setIsEditorShown] = useState(
    isBigScreen ? true : false
  );

  const handleMenuOpen = () => {
    setIsEditorShown(!isEditorShown);
  };
  
  return (
    <>
      <Head>
        <title>Simple Web Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bar toggleMenu={handleMenuOpen} />
      <main>
        <Preview />
        <EditorForm
          isBigScreen={isBigScreen}
          isDrawerOpened={isEditorShown}
          onClose={handleMenuOpen}
        />
      </main>
    </>
  );
}
